services:
  redis-master:
    image: redis:latest
    container_name: redis-master
    ports:
      - 6379:6379
  redis-slave1:
    image: redis:latest
    container_name: redis-slave
    privileged: true
    ports:
      - 6380:6379
    volumes:
      - ./conf:/usr/local/etc/redis
    command: redis-server /usr/local/etc/redis.conf --slaveof redis-master 6379 --port 6380 --replica-priority 50
  redis-slave2:
    image: redis:latest
    container_name: redis-slave2
    privileged: true
    ports:
      - 6381:6379
    volumes:
      - ./conf:/usr/local/etc/redis.conf
    command: redis-server /usr/local/etc/redis.conf --slaveof redis-master 6379 --port 6381
  redis-sentinel:
    image: 'bitnami/redis-sentinel:latest'
    environment:
      - REDIS_SENTINEL_DOWN_AFTER_MILLISECONDS=3000
      - REDIS_MASTER_HOST=redis-master # local device en0 IP
      - REDIS_MASTER_PORT_NUMBER=6379
      - REDIS_MASTER_SET=mymaster
      - REDIS_SENTINEL_QUORUM=2
      - REDIS_SENTINEL_RESOLVE_HOSTNAMES=yes
    depends_on:
      - redis-master2
    ports:
      - 6381:6381
      - redis-slave1
      - redis-slave2
    ports:
      - '26379-26381:26379'
    networks:
      - redis_network